### ISSUE TITLE
'charmap' codec can't decode js_file

### ISSUE THREAD

**Issue by juanblasmdq** [Mayur57/twitter-nuke#1]
Hello! I got here from your Reddit's post

I'm trying to take advantage of the great work you've done but it seems that there is an error processing the twitter.json file

I've tried using different encoding options but code will crash later

![image](https://user-images.githubusercontent.com/83381578/126045872-ba3f4d34-6ee7-4a43-8ab3-7dc9f17ec226.png)

The error I get:
---->  'charmap' codec can't decode byte 0x81 in position 7163: character maps to <undefined>

I wish I could fix the problem myself but I am new to Python and don't have much experience with json files and encoding

Regards,
Juan

**Comment by mayur57** [comment]
Hello Juan,
Thanks for posting a detailed description of the issue you are facing. To assess the issue fully, I'll require you to do the following things:

- Check if the path you are passing as `JS_FILE` is actually a valid `.js` file. (Common mistake is to pass a directory as the path)
- If it is, please consider posting the `.js` file here so that I can inspect it.

Also, I would like to thank you for the time you took out to post this issue and contributing towards making this project better. 🍺
Mayur B.

**Comment by juanblasmdq** [comment]
Hi Mayur! Thanks for the response

I verified that the path to the .js file is correct;
I then run the code in debbuger mode and inspect the .js file position by position each time an error arise and looks like the problem was related to Spanish and other special characters like Á❥❁ Í etc. included in the .js file

Now, that problem seems to be solved by removing those characters, but the script continue but cannot delete the tweets.

Terminal output:
Thread started for deletion. Thread #1
Thread started for deletion. Thread #2
Thread started for deletion. Thread #3
--> Successfully deleted 1281 tweets.
--> Successfully skipped 0 tweets from deletion.
--> Number of threads used: 281 of batch size 500 each.

ERROR: ---Read-only application cannot POST.295337138747232256
ERROR: ---Read-only application cannot POST.467074477604745216
etc...
**This ERROR arises multiple times and no tweet was deleted.**

Do you think it may be related to certain permissions that the API that I accessed has?
Thanks
Juan

**Comment by juanblasmdq** [comment]
Hi again, sorry for bothering

I solve the issue by changing app settings following this post:
https://stackoverflow.com/questions/8389796/why-this-error-read-only-application-cannot-post

Tweets deleted successfully!
Thanks,
Juan

**Comment by mayur57** [comment]
> Hi again, sorry for bothering
> 
> I solve the issue by changing app settings following this post:
> https://stackoverflow.com/questions/8389796/why-this-error-read-only-application-cannot-post
> 
> Tweets deleted successfully!
> Thanks,
> Juan

Glad it worked for you! I'll update the README to better convey the fact that API keys need to be generated with Read+Write access and also add a method to replace error causing chars in a future release. Thank you for your contribution.
